# CMake generated Testfile for 
# Source directory: /usr/ns-3-dev/src/fd-net-device/examples
# Build directory: /usr/ns-3-dev/cmake-cache/src/fd-net-device/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-dummy-network "ns3.39-dummy-network-optimized")
set_tests_properties(ctest-dummy-network PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;3;build_lib_example;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd2fd-onoff "ns3.39-fd2fd-onoff-optimized")
set_tests_properties(ctest-fd2fd-onoff PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;12;build_lib_example;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-realtime-dummy-network "ns3.39-realtime-dummy-network-optimized")
set_tests_properties(ctest-realtime-dummy-network PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;21;build_lib_example;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-realtime-fd2fd-onoff "ns3.39-realtime-fd2fd-onoff-optimized")
set_tests_properties(ctest-realtime-fd2fd-onoff PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;31;build_lib_example;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd-emu-ping "ns3.39-fd-emu-ping-optimized")
set_tests_properties(ctest-fd-emu-ping PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;41;build_lib_example;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd-emu-udp-echo "ns3.39-fd-emu-udp-echo-optimized")
set_tests_properties(ctest-fd-emu-udp-echo PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;50;build_lib_example;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd-emu-onoff "ns3.39-fd-emu-onoff-optimized")
set_tests_properties(ctest-fd-emu-onoff PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;59;build_lib_example;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd-emu-send "ns3.39-fd-emu-send-optimized")
set_tests_properties(ctest-fd-emu-send PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;68;build_lib_example;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd-emu-tc "ns3.39-fd-emu-tc-optimized")
set_tests_properties(ctest-fd-emu-tc PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;79;build_lib_example;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd-tap-ping "ns3.39-fd-tap-ping-optimized")
set_tests_properties(ctest-fd-tap-ping PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;92;build_lib_example;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
add_test(ctest-fd-tap-ping6 "ns3.39-fd-tap-ping6-optimized")
set_tests_properties(ctest-fd-tap-ping6 PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/fd-net-device/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;101;build_lib_example;/usr/ns-3-dev/src/fd-net-device/examples/CMakeLists.txt;0;")
