# CMake generated Testfile for 
# Source directory: /usr/ns-3-dev/src/stats/examples
# Build directory: /usr/ns-3-dev/cmake-cache/src/stats/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-time-probe-example "ns3.39-time-probe-example-optimized")
set_tests_properties(ctest-time-probe-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/stats/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/stats/examples/CMakeLists.txt;1;build_lib_example;/usr/ns-3-dev/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-example "ns3.39-gnuplot-example-optimized")
set_tests_properties(ctest-gnuplot-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/stats/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/stats/examples/CMakeLists.txt;20;build_lib_example;/usr/ns-3-dev/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-double-probe-example "ns3.39-double-probe-example-optimized")
set_tests_properties(ctest-double-probe-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/stats/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/stats/examples/CMakeLists.txt;20;build_lib_example;/usr/ns-3-dev/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-aggregator-example "ns3.39-gnuplot-aggregator-example-optimized")
set_tests_properties(ctest-gnuplot-aggregator-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/stats/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/stats/examples/CMakeLists.txt;20;build_lib_example;/usr/ns-3-dev/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-helper-example "ns3.39-gnuplot-helper-example-optimized")
set_tests_properties(ctest-gnuplot-helper-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/stats/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/stats/examples/CMakeLists.txt;20;build_lib_example;/usr/ns-3-dev/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-file-aggregator-example "ns3.39-file-aggregator-example-optimized")
set_tests_properties(ctest-file-aggregator-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/stats/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/stats/examples/CMakeLists.txt;20;build_lib_example;/usr/ns-3-dev/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-file-helper-example "ns3.39-file-helper-example-optimized")
set_tests_properties(ctest-file-helper-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/stats/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/stats/examples/CMakeLists.txt;20;build_lib_example;/usr/ns-3-dev/src/stats/examples/CMakeLists.txt;0;")
