# CMake generated Testfile for 
# Source directory: /usr/ns-3-dev/src/spectrum/examples
# Build directory: /usr/ns-3-dev/cmake-cache/src/spectrum/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-adhoc-aloha-ideal-phy "ns3.39-adhoc-aloha-ideal-phy-optimized")
set_tests_properties(ctest-adhoc-aloha-ideal-phy PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/spectrum/examples/CMakeLists.txt;1;build_lib_example;/usr/ns-3-dev/src/spectrum/examples/CMakeLists.txt;0;")
add_test(ctest-adhoc-aloha-ideal-phy-matrix-propagation-loss-model "ns3.39-adhoc-aloha-ideal-phy-matrix-propagation-loss-model-optimized")
set_tests_properties(ctest-adhoc-aloha-ideal-phy-matrix-propagation-loss-model PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/spectrum/examples/CMakeLists.txt;11;build_lib_example;/usr/ns-3-dev/src/spectrum/examples/CMakeLists.txt;0;")
add_test(ctest-adhoc-aloha-ideal-phy-with-microwave-oven "ns3.39-adhoc-aloha-ideal-phy-with-microwave-oven-optimized")
set_tests_properties(ctest-adhoc-aloha-ideal-phy-with-microwave-oven PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/spectrum/examples/CMakeLists.txt;21;build_lib_example;/usr/ns-3-dev/src/spectrum/examples/CMakeLists.txt;0;")
add_test(ctest-tv-trans-example "ns3.39-tv-trans-example-optimized")
set_tests_properties(ctest-tv-trans-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/spectrum/examples/CMakeLists.txt;31;build_lib_example;/usr/ns-3-dev/src/spectrum/examples/CMakeLists.txt;0;")
add_test(ctest-tv-trans-regional-example "ns3.39-tv-trans-regional-example-optimized")
set_tests_properties(ctest-tv-trans-regional-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/spectrum/examples/CMakeLists.txt;40;build_lib_example;/usr/ns-3-dev/src/spectrum/examples/CMakeLists.txt;0;")
add_test(ctest-three-gpp-channel-example "ns3.39-three-gpp-channel-example-optimized")
set_tests_properties(ctest-three-gpp-channel-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/spectrum/examples/CMakeLists.txt;49;build_lib_example;/usr/ns-3-dev/src/spectrum/examples/CMakeLists.txt;0;")
add_test(ctest-three-gpp-two-ray-channel-calibration "ns3.39-three-gpp-two-ray-channel-calibration-optimized")
set_tests_properties(ctest-three-gpp-two-ray-channel-calibration PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/spectrum/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/spectrum/examples/CMakeLists.txt;59;build_lib_example;/usr/ns-3-dev/src/spectrum/examples/CMakeLists.txt;0;")
