# CMake generated Testfile for 
# Source directory: /usr/ns-3-dev/contrib/ofswitch13/examples
# Build directory: /usr/ns-3-dev/cmake-cache/contrib/ofswitch13/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-ofswitch13-first "ns3.39-ofswitch13-first-optimized")
set_tests_properties(ctest-ofswitch13-first PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/contrib/ofswitch13/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/contrib/ofswitch13/examples/CMakeLists.txt;1;build_lib_example;/usr/ns-3-dev/contrib/ofswitch13/examples/CMakeLists.txt;0;")
add_test(ctest-ofswitch13-custom-switch "ns3.39-ofswitch13-custom-switch-optimized")
set_tests_properties(ctest-ofswitch13-custom-switch PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/contrib/ofswitch13/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/contrib/ofswitch13/examples/CMakeLists.txt;9;build_lib_example;/usr/ns-3-dev/contrib/ofswitch13/examples/CMakeLists.txt;0;")
add_test(ctest-ofswitch13-multiple-controllers "ns3.39-ofswitch13-multiple-controllers-optimized")
set_tests_properties(ctest-ofswitch13-multiple-controllers PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/contrib/ofswitch13/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/contrib/ofswitch13/examples/CMakeLists.txt;17;build_lib_example;/usr/ns-3-dev/contrib/ofswitch13/examples/CMakeLists.txt;0;")
add_test(ctest-ofswitch13-multiple-domains "ns3.39-ofswitch13-multiple-domains-optimized")
set_tests_properties(ctest-ofswitch13-multiple-domains PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/contrib/ofswitch13/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/contrib/ofswitch13/examples/CMakeLists.txt;25;build_lib_example;/usr/ns-3-dev/contrib/ofswitch13/examples/CMakeLists.txt;0;")
add_test(ctest-ofswitch13-single-domain "ns3.39-ofswitch13-single-domain-optimized")
set_tests_properties(ctest-ofswitch13-single-domain PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/contrib/ofswitch13/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/contrib/ofswitch13/examples/CMakeLists.txt;33;build_lib_example;/usr/ns-3-dev/contrib/ofswitch13/examples/CMakeLists.txt;0;")
add_test(ctest-ofswitch13-external-controller "ns3.39-ofswitch13-external-controller-optimized")
set_tests_properties(ctest-ofswitch13-external-controller PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/contrib/ofswitch13/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/contrib/ofswitch13/examples/CMakeLists.txt;41;build_lib_example;/usr/ns-3-dev/contrib/ofswitch13/examples/CMakeLists.txt;0;")
add_test(ctest-ofswitch13-qos-controller "ns3.39-ofswitch13-qos-controller-optimized")
set_tests_properties(ctest-ofswitch13-qos-controller PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/contrib/ofswitch13/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/contrib/ofswitch13/examples/CMakeLists.txt;50;build_lib_example;/usr/ns-3-dev/contrib/ofswitch13/examples/CMakeLists.txt;0;")
add_test(ctest-ofswitch13-logical-port "ns3.39-ofswitch13-logical-port-optimized")
set_tests_properties(ctest-ofswitch13-logical-port PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/contrib/ofswitch13/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/contrib/ofswitch13/examples/CMakeLists.txt;59;build_lib_example;/usr/ns-3-dev/contrib/ofswitch13/examples/CMakeLists.txt;0;")
