# CMake generated Testfile for 
# Source directory: /usr/ns-3-dev/src/traffic-control/examples
# Build directory: /usr/ns-3-dev/cmake-cache/src/traffic-control/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-red-tests "ns3.39-red-tests-optimized")
set_tests_properties(ctest-red-tests PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/traffic-control/examples/CMakeLists.txt;1;build_lib_example;/usr/ns-3-dev/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-red-vs-ared "ns3.39-red-vs-ared-optimized")
set_tests_properties(ctest-red-vs-ared PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/traffic-control/examples/CMakeLists.txt;12;build_lib_example;/usr/ns-3-dev/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-adaptive-red-tests "ns3.39-adaptive-red-tests-optimized")
set_tests_properties(ctest-adaptive-red-tests PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/traffic-control/examples/CMakeLists.txt;23;build_lib_example;/usr/ns-3-dev/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-pfifo-vs-red "ns3.39-pfifo-vs-red-optimized")
set_tests_properties(ctest-pfifo-vs-red PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/traffic-control/examples/CMakeLists.txt;34;build_lib_example;/usr/ns-3-dev/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-codel-vs-pfifo-basic-test "ns3.39-codel-vs-pfifo-basic-test-optimized")
set_tests_properties(ctest-codel-vs-pfifo-basic-test PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/traffic-control/examples/CMakeLists.txt;45;build_lib_example;/usr/ns-3-dev/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-codel-vs-pfifo-asymmetric "ns3.39-codel-vs-pfifo-asymmetric-optimized")
set_tests_properties(ctest-codel-vs-pfifo-asymmetric PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/traffic-control/examples/CMakeLists.txt;56;build_lib_example;/usr/ns-3-dev/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-pie-example "ns3.39-pie-example-optimized")
set_tests_properties(ctest-pie-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/traffic-control/examples/CMakeLists.txt;68;build_lib_example;/usr/ns-3-dev/src/traffic-control/examples/CMakeLists.txt;0;")
add_test(ctest-fqcodel-l4s-example "ns3.39-fqcodel-l4s-example-optimized")
set_tests_properties(ctest-fqcodel-l4s-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/traffic-control/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/traffic-control/examples/CMakeLists.txt;79;build_lib_example;/usr/ns-3-dev/src/traffic-control/examples/CMakeLists.txt;0;")
