# CMake generated Testfile for 
# Source directory: /usr/ns-3-dev/src/netanim/examples
# Build directory: /usr/ns-3-dev/cmake-cache/src/netanim/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-dumbbell-animation "ns3.39-dumbbell-animation-optimized")
set_tests_properties(ctest-dumbbell-animation PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/usr/ns-3-dev/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-grid-animation "ns3.39-grid-animation-optimized")
set_tests_properties(ctest-grid-animation PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/usr/ns-3-dev/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-star-animation "ns3.39-star-animation-optimized")
set_tests_properties(ctest-star-animation PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/usr/ns-3-dev/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-colors-link-description "ns3.39-colors-link-description-optimized")
set_tests_properties(ctest-colors-link-description PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/usr/ns-3-dev/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-resources-counters "ns3.39-resources-counters-optimized")
set_tests_properties(ctest-resources-counters PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/netanim/examples/CMakeLists.txt;13;build_lib_example;/usr/ns-3-dev/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-wireless-animation "ns3.39-wireless-animation-optimized")
set_tests_properties(ctest-wireless-animation PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/netanim/examples/CMakeLists.txt;23;build_lib_example;/usr/ns-3-dev/src/netanim/examples/CMakeLists.txt;0;")
add_test(ctest-uan-animation "ns3.39-uan-animation-optimized")
set_tests_properties(ctest-uan-animation PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/netanim/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/netanim/examples/CMakeLists.txt;36;build_lib_example;/usr/ns-3-dev/src/netanim/examples/CMakeLists.txt;0;")
