# CMake generated Testfile for 
# Source directory: /usr/ns-3-dev/examples/tcp
# Build directory: /usr/ns-3-dev/cmake-cache/examples/tcp
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-tcp-large-transfer "ns3.39-tcp-large-transfer-optimized")
set_tests_properties(ctest-tcp-large-transfer PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/tcp/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;1;build_example;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-star-server "ns3.39-tcp-star-server-optimized")
set_tests_properties(ctest-tcp-star-server PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/tcp/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;10;build_example;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-star "ns3.39-star-optimized")
set_tests_properties(ctest-star PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/tcp/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;19;build_example;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-bbr-example "ns3.39-tcp-bbr-example-optimized")
set_tests_properties(ctest-tcp-bbr-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/tcp/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;30;build_example;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-bulk-send "ns3.39-tcp-bulk-send-optimized")
set_tests_properties(ctest-tcp-bulk-send PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/tcp/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;43;build_example;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-pcap-nanosec-example "ns3.39-tcp-pcap-nanosec-example-optimized")
set_tests_properties(ctest-tcp-pcap-nanosec-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/tcp/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;52;build_example;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-variants-comparison "ns3.39-tcp-variants-comparison-optimized")
set_tests_properties(ctest-tcp-variants-comparison PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/tcp/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;61;build_example;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-pacing "ns3.39-tcp-pacing-optimized")
set_tests_properties(ctest-tcp-pacing PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/tcp/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;71;build_example;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-linux-reno "ns3.39-tcp-linux-reno-optimized")
set_tests_properties(ctest-tcp-linux-reno PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/tcp/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;81;build_example;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-tcp-validation "ns3.39-tcp-validation-optimized")
set_tests_properties(ctest-tcp-validation PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/tcp/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;92;build_example;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;0;")
add_test(ctest-dctcp-example "ns3.39-dctcp-example-optimized")
set_tests_properties(ctest-dctcp-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/tcp/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;104;build_example;/usr/ns-3-dev/examples/tcp/CMakeLists.txt;0;")
