# CMake generated Testfile for 
# Source directory: /usr/ns-3-dev/examples/ipv6
# Build directory: /usr/ns-3-dev/cmake-cache/examples/ipv6
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-fragmentation-ipv6 "ns3.39-fragmentation-ipv6-optimized")
set_tests_properties(ctest-fragmentation-ipv6 PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/ipv6/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/ipv6/CMakeLists.txt;1;build_example;/usr/ns-3-dev/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-fragmentation-ipv6-two-MTU "ns3.39-fragmentation-ipv6-two-MTU-optimized")
set_tests_properties(ctest-fragmentation-ipv6-two-MTU PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/ipv6/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/ipv6/CMakeLists.txt;10;build_example;/usr/ns-3-dev/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-icmpv6-redirect "ns3.39-icmpv6-redirect-optimized")
set_tests_properties(ctest-icmpv6-redirect PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/ipv6/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/ipv6/CMakeLists.txt;19;build_example;/usr/ns-3-dev/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-loose-routing-ipv6 "ns3.39-loose-routing-ipv6-optimized")
set_tests_properties(ctest-loose-routing-ipv6 PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/ipv6/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/ipv6/CMakeLists.txt;28;build_example;/usr/ns-3-dev/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-ping6-example "ns3.39-ping6-example-optimized")
set_tests_properties(ctest-ping6-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/ipv6/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/ipv6/CMakeLists.txt;37;build_example;/usr/ns-3-dev/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-radvd-one-prefix "ns3.39-radvd-one-prefix-optimized")
set_tests_properties(ctest-radvd-one-prefix PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/ipv6/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/ipv6/CMakeLists.txt;46;build_example;/usr/ns-3-dev/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-radvd-two-prefix "ns3.39-radvd-two-prefix-optimized")
set_tests_properties(ctest-radvd-two-prefix PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/ipv6/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/ipv6/CMakeLists.txt;55;build_example;/usr/ns-3-dev/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-test-ipv6 "ns3.39-test-ipv6-optimized")
set_tests_properties(ctest-test-ipv6 PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/ipv6/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/ipv6/CMakeLists.txt;64;build_example;/usr/ns-3-dev/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-wsn-ping6 "ns3.39-wsn-ping6-optimized")
set_tests_properties(ctest-wsn-ping6 PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/ipv6/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/ipv6/CMakeLists.txt;71;build_example;/usr/ns-3-dev/examples/ipv6/CMakeLists.txt;0;")
add_test(ctest-fragmentation-ipv6-PMTU "ns3.39-fragmentation-ipv6-PMTU-optimized")
set_tests_properties(ctest-fragmentation-ipv6-PMTU PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/ipv6/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/ipv6/CMakeLists.txt;82;build_example;/usr/ns-3-dev/examples/ipv6/CMakeLists.txt;0;")
