# CMake generated Testfile for 
# Source directory: /usr/ns-3-dev/src/lr-wpan/examples
# Build directory: /usr/ns-3-dev/cmake-cache/src/lr-wpan/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-lr-wpan-data "ns3.39-lr-wpan-data-optimized")
set_tests_properties(ctest-lr-wpan-data PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;15;build_lib_example;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-mlme "ns3.39-lr-wpan-mlme-optimized")
set_tests_properties(ctest-lr-wpan-mlme PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;15;build_lib_example;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-packet-print "ns3.39-lr-wpan-packet-print-optimized")
set_tests_properties(ctest-lr-wpan-packet-print PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;15;build_lib_example;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-phy-test "ns3.39-lr-wpan-phy-test-optimized")
set_tests_properties(ctest-lr-wpan-phy-test PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;15;build_lib_example;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-ed-scan "ns3.39-lr-wpan-ed-scan-optimized")
set_tests_properties(ctest-lr-wpan-ed-scan PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;15;build_lib_example;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-active-scan "ns3.39-lr-wpan-active-scan-optimized")
set_tests_properties(ctest-lr-wpan-active-scan PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;15;build_lib_example;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-orphan-scan "ns3.39-lr-wpan-orphan-scan-optimized")
set_tests_properties(ctest-lr-wpan-orphan-scan PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;15;build_lib_example;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-error-distance-plot "ns3.39-lr-wpan-error-distance-plot-optimized")
set_tests_properties(ctest-lr-wpan-error-distance-plot PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;22;build_lib_example;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-error-model-plot "ns3.39-lr-wpan-error-model-plot-optimized")
set_tests_properties(ctest-lr-wpan-error-model-plot PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;29;build_lib_example;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-bootstrap "ns3.39-lr-wpan-bootstrap-optimized")
set_tests_properties(ctest-lr-wpan-bootstrap PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;36;build_lib_example;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;0;")
add_test(ctest-lr-wpan-per-plot "ns3.39-lr-wpan-per-plot-optimized")
set_tests_properties(ctest-lr-wpan-per-plot PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/lr-wpan/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;43;build_lib_example;/usr/ns-3-dev/src/lr-wpan/examples/CMakeLists.txt;0;")
