# CMake generated Testfile for 
# Source directory: /usr/ns-3-dev/src/uan/examples
# Build directory: /usr/ns-3-dev/cmake-cache/src/uan/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-uan-cw-example "ns3.39-uan-cw-example-optimized")
set_tests_properties(ctest-uan-cw-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/uan/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/uan/examples/CMakeLists.txt;12;build_lib_example;/usr/ns-3-dev/src/uan/examples/CMakeLists.txt;0;")
add_test(ctest-uan-rc-example "ns3.39-uan-rc-example-optimized")
set_tests_properties(ctest-uan-rc-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/uan/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/uan/examples/CMakeLists.txt;12;build_lib_example;/usr/ns-3-dev/src/uan/examples/CMakeLists.txt;0;")
add_test(ctest-uan-ipv4-example "ns3.39-uan-ipv4-example-optimized")
set_tests_properties(ctest-uan-ipv4-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/uan/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/uan/examples/CMakeLists.txt;12;build_lib_example;/usr/ns-3-dev/src/uan/examples/CMakeLists.txt;0;")
add_test(ctest-uan-ipv6-example "ns3.39-uan-ipv6-example-optimized")
set_tests_properties(ctest-uan-ipv6-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/uan/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/uan/examples/CMakeLists.txt;12;build_lib_example;/usr/ns-3-dev/src/uan/examples/CMakeLists.txt;0;")
add_test(ctest-uan-raw-example "ns3.39-uan-raw-example-optimized")
set_tests_properties(ctest-uan-raw-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/uan/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/uan/examples/CMakeLists.txt;12;build_lib_example;/usr/ns-3-dev/src/uan/examples/CMakeLists.txt;0;")
add_test(ctest-uan-6lowpan-example "ns3.39-uan-6lowpan-example-optimized")
set_tests_properties(ctest-uan-6lowpan-example PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/src/uan/examples/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/usr/ns-3-dev/src/uan/examples/CMakeLists.txt;24;build_lib_example;/usr/ns-3-dev/src/uan/examples/CMakeLists.txt;0;")
