# CMake generated Testfile for 
# Source directory: /usr/ns-3-dev/examples/routing
# Build directory: /usr/ns-3-dev/cmake-cache/examples/routing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-dynamic-global-routing "ns3.39-dynamic-global-routing-optimized")
set_tests_properties(ctest-dynamic-global-routing PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/routing/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/routing/CMakeLists.txt;1;build_example;/usr/ns-3-dev/examples/routing/CMakeLists.txt;0;")
add_test(ctest-static-routing-slash32 "ns3.39-static-routing-slash32-optimized")
set_tests_properties(ctest-static-routing-slash32 PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/routing/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/routing/CMakeLists.txt;11;build_example;/usr/ns-3-dev/examples/routing/CMakeLists.txt;0;")
add_test(ctest-global-routing-slash32 "ns3.39-global-routing-slash32-optimized")
set_tests_properties(ctest-global-routing-slash32 PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/routing/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/routing/CMakeLists.txt;21;build_example;/usr/ns-3-dev/examples/routing/CMakeLists.txt;0;")
add_test(ctest-global-injection-slash32 "ns3.39-global-injection-slash32-optimized")
set_tests_properties(ctest-global-injection-slash32 PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/routing/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/routing/CMakeLists.txt;31;build_example;/usr/ns-3-dev/examples/routing/CMakeLists.txt;0;")
add_test(ctest-simple-global-routing "ns3.39-simple-global-routing-optimized")
set_tests_properties(ctest-simple-global-routing PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/routing/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/routing/CMakeLists.txt;41;build_example;/usr/ns-3-dev/examples/routing/CMakeLists.txt;0;")
add_test(ctest-simple-alternate-routing "ns3.39-simple-alternate-routing-optimized")
set_tests_properties(ctest-simple-alternate-routing PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/routing/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/routing/CMakeLists.txt;51;build_example;/usr/ns-3-dev/examples/routing/CMakeLists.txt;0;")
add_test(ctest-mixed-global-routing "ns3.39-mixed-global-routing-optimized")
set_tests_properties(ctest-mixed-global-routing PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/routing/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/routing/CMakeLists.txt;60;build_example;/usr/ns-3-dev/examples/routing/CMakeLists.txt;0;")
add_test(ctest-simple-routing-ping6 "ns3.39-simple-routing-ping6-optimized")
set_tests_properties(ctest-simple-routing-ping6 PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/routing/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/routing/CMakeLists.txt;70;build_example;/usr/ns-3-dev/examples/routing/CMakeLists.txt;0;")
add_test(ctest-manet-routing-compare "ns3.39-manet-routing-compare-optimized")
set_tests_properties(ctest-manet-routing-compare PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/routing/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/routing/CMakeLists.txt;79;build_example;/usr/ns-3-dev/examples/routing/CMakeLists.txt;0;")
add_test(ctest-ripng-simple-network "ns3.39-ripng-simple-network-optimized")
set_tests_properties(ctest-ripng-simple-network PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/routing/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/routing/CMakeLists.txt;93;build_example;/usr/ns-3-dev/examples/routing/CMakeLists.txt;0;")
add_test(ctest-rip-simple-network "ns3.39-rip-simple-network-optimized")
set_tests_properties(ctest-rip-simple-network PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/routing/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/routing/CMakeLists.txt;102;build_example;/usr/ns-3-dev/examples/routing/CMakeLists.txt;0;")
add_test(ctest-global-routing-multi-switch-plus-router "ns3.39-global-routing-multi-switch-plus-router-optimized")
set_tests_properties(ctest-global-routing-multi-switch-plus-router PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/routing/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/routing/CMakeLists.txt;111;build_example;/usr/ns-3-dev/examples/routing/CMakeLists.txt;0;")
add_test(ctest-simple-multicast-flooding "ns3.39-simple-multicast-flooding-optimized")
set_tests_properties(ctest-simple-multicast-flooding PROPERTIES  WORKING_DIRECTORY "/usr/ns-3-dev/build/examples/routing/" _BACKTRACE_TRIPLES "/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1584;add_test;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/usr/ns-3-dev/build-support/macros-and-definitions.cmake;1812;build_exec;/usr/ns-3-dev/examples/routing/CMakeLists.txt;126;build_example;/usr/ns-3-dev/examples/routing/CMakeLists.txt;0;")
